# Generated by Django 4.0.6 on 2022-08-29 11:22

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='formData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitnumber', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date', models.DateField()),
                ('typeOfWork', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None)),
                ('numberOfPerson', models.IntegerField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('equipment', models.CharField(blank=True, max_length=200, null=True)),
                ('toolRequired', models.CharField(blank=True, max_length=200, null=True)),
                ('workDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('ppeRequired', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('other_ppe', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('verified_by_person1', models.BooleanField(default=False, null=True)),
                ('verified_by_person2', models.BooleanField(default=False, null=True)),
                ('verified_by_person3', models.BooleanField(default=False, null=True)),
                ('notify_person1', models.BooleanField(default=True, null=True)),
                ('notify_person2', models.BooleanField(default=False, null=True)),
                ('notify_person3', models.BooleanField(default=False, null=True)),
                ('newFlag', models.BooleanField(default=True, null=True, verbose_name='New Work Permit')),
                ('oldFlag', models.BooleanField(default=False, null=True, verbose_name='Old Work Permit')),
                ('tocloseFlag', models.BooleanField(default=False, null=True, verbose_name='Closed Work Permit')),
                ('closedByLoggedUser', models.BooleanField(default=False, null=True)),
                ('closedByPerson1', models.BooleanField(default=False, null=True)),
                ('closedByPerson2', models.BooleanField(default=False, null=True)),
                ('closedByPerson3', models.BooleanField(default=False, null=True)),
                ('completedFlag', models.BooleanField(default=False, null=True, verbose_name='Completed Work Permit')),
                ('new_flag_date_created', models.DateField(blank=True, null=True)),
                ('toclose_flag_date_created', models.DateField(blank=True, null=True)),
                ('old_flag_date_created', models.DateField(blank=True, null=True)),
                ('completed_flag_date_created', models.DateField(blank=True, null=True)),
                ('q1', models.CharField(blank=True, max_length=500, null=True)),
                ('q2', models.CharField(blank=True, max_length=500, null=True)),
                ('q3', models.CharField(blank=True, max_length=500, null=True)),
                ('q4', models.CharField(blank=True, max_length=500, null=True)),
                ('q5', models.CharField(blank=True, max_length=500, null=True)),
                ('q6', models.CharField(blank=True, max_length=500, null=True)),
                ('q7', models.CharField(blank=True, max_length=500, null=True)),
                ('q8', models.CharField(blank=True, max_length=500, null=True)),
                ('q9', models.CharField(blank=True, max_length=500, null=True)),
                ('q10', models.CharField(blank=True, max_length=500, null=True)),
                ('q11', models.CharField(blank=True, max_length=500, null=True)),
                ('q12', models.CharField(blank=True, max_length=500, null=True)),
                ('q13', models.CharField(blank=True, max_length=500, null=True)),
                ('q14', models.CharField(blank=True, max_length=500, null=True)),
                ('q15', models.CharField(blank=True, max_length=500, null=True)),
                ('q16', models.CharField(blank=True, max_length=500, null=True)),
                ('q17', models.CharField(blank=True, max_length=500, null=True)),
                ('rejectFlag', models.BooleanField(default=False, null=True, verbose_name='Rejected Work Permit')),
                ('rejected_flag_date_created', models.DateField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Work Permit',
            },
        ),
        migrations.CreateModel(
            name='issueAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyName', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Agency Name',
            },
        ),
        migrations.CreateModel(
            name='PermitNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='userLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_login_user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('permit_id', models.CharField(blank=True, max_length=255, null=True)),
                ('permit_initiator', models.CharField(blank=True, max_length=255, null=True)),
                ('hod_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hod_encharge', models.CharField(blank=True, max_length=255, null=True)),
                ('he_she_id', models.CharField(blank=True, max_length=255, null=True)),
                ('he_she', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=235)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('is_first_login', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Create New User',
            },
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PGPapi.userlocation')),
                ('userName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PGPapi.userrole')),
            ],
            options={
                'verbose_name_plural': 'User detail',
            },
        ),
        migrations.CreateModel(
            name='NotificationForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_notification', models.BooleanField(default=False, null=True)),
                ('close_notification', models.BooleanField(default=False, null=True)),
                ('complete_notification', models.BooleanField(default=False, null=True)),
                ('reject_notification', models.BooleanField(default=False, null=True)),
                ('verified_by_all', models.BooleanField(default=False, null=True)),
                ('closed_by_all', models.BooleanField(default=False, null=True)),
                ('message', models.CharField(default='', max_length=255)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGPapi.formdata')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='formdata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGPapi.userlocation'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='loggedPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdata',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdata',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdata',
            name='person3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdata',
            name='workingAgency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGPapi.issueagency'),
        ),
        migrations.CreateModel(
            name='fcmTokenFirebase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(blank=True, max_length=500, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
