# Generated by Django 4.0.6 on 2022-08-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGPapi', '0003_formdata_approve_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='reason_for_status_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
